### ISSUE TITLE
Garden exception during bosh shutdown

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/guardian#88]
Versions:
observed on: 
bosh-vsphere-esxi-ubuntu-trusty-go_agent/3421.6 and 3363.14 
garden-runc 1.0.4

When deploy a BOSH release, i frequently get

```   Failed updating instance diego_cell > diego_cell/88bc92e1-f2cc-4c3e-802c-1927453d8cdd (0) (canary): Action Failed get_task: Task 4ca73da5-0b63-489d-5369-632a15f6461c result: Stopping Monitored Services: Stopping services '[garden]' errored (00:06:31)

Error 450001: Action Failed get_task: Task 4ca73da5-0b63-489d-5369-632a15f6461c result: Stopping Monitored Services: Stopping services
'[garden]' errored
```

And garden.stderr.log always contains 

```SIGQUIT: quit
PC=0x460251 m=0

goroutine 0 [idle]:
runtime.futex(0xee5490, 0x0, 0x0, 0x0, 0x7ffc00000000, 0x0, 0x0, 0x0, 0x7ffcab765698, 0x40f8b2, ...)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0xee5490, 0x0, 0xffffffffffffffff)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xee5490)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/proc.go:1594 +0xad
runtime.findrunnable(0xc42001c000, 0x0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/proc.go:2021 +0x228
runtime.schedule()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/proc.go:2120 +0x14c
runtime.goexit0(0xc42008e340)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/proc.go:2257 +0x180
runtime.mcall(0x7ffcab765840)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [chan receive, 942 minutes]:
code.cloudfoundry.org/guardian/guardiancmd.(*GuardianCommand).Execute(0xc42020edc0, 0xc420243860, 0x0, 0x1a, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/guardiancmd/command.go:236 +0xb8
main.main()
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/cmd/guardian/main.go:22 +0xe4

goroutine 17 [syscall, 942 minutes, locked to thread]:
runtime.goexit()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0xeca0c0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select]:
github.com/tedsuo/ifrit/sigmon.sigmon.Run(0xc420208e60, 0x2, 0x2, 0xec2c80, 0xc42020edc0, 0xc4202025a0, 0xc420202600, 0x0, 0x0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/sigmon/sigmon.go:35 +0x317
github.com/tedsuo/ifrit/sigmon.(*sigmon).Run(0xc4201edd10, 0xc4202025a0, 0xc420202600, 0x0, 0x0)
	<autogenerated>:1 +0x82
github.com/tedsuo/ifrit.(*process).run(0xc4201eeb80)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:71 +0x49
created by github.com/tedsuo/ifrit.Background
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:49 +0x14e

goroutine 19 [chan receive, 942 minutes]:
github.com/tedsuo/ifrit.(*process).Wait.func1(0xc4201eeb80, 0xc4202026c0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:83 +0x44
created by github.com/tedsuo/ifrit.(*process).Wait
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:85 +0x67

goroutine 34 [select, 942 minutes, locked to thread]:
runtime.gopark(0xa694e8, 0x0, 0xa0b341, 0x6, 0x18, 0x2)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42025a730, 0x0, 0x18)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42025a730)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/asm_amd64.s:2086 +0x1

goroutine 35 [semacquire]:
sync.runtime_Semacquire(0xc4202afd5c)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4202afd50)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/sync/waitgroup.go:131 +0x97
code.cloudfoundry.org/garden/server.(*GardenServer).Stop(0xc4202a60b0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/server.go:209 +0x346
code.cloudfoundry.org/guardian/guardiancmd.(*GuardianCommand).Run(0xc42020edc0, 0xc42024c180, 0xc42024c1e0, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/guardiancmd/command.go:342 +0xd86
github.com/tedsuo/ifrit.(*process).run(0xc420200040)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:71 +0x49
created by github.com/tedsuo/ifrit.Background
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:49 +0x14e

goroutine 36 [chan receive, 942 minutes]:
github.com/tedsuo/ifrit.(*process).Wait.func1(0xc420200040, 0xc42024c2a0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:83 +0x44
created by github.com/tedsuo/ifrit.(*process).Wait
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:85 +0x67

goroutine 7 [select]:
code.cloudfoundry.org/guardian/metrics.PeriodicMetronNotifier.Start.func1(0xec8a00, 0xc420028128, 0xecee00, 0xc42024d620, 0xdf8475800, 0xecee00, 0xc42024c300, 0xecd300, 0xf01098, 0xecd060, ...)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/metrics/periodic_metron_notifier.go:68 +0x4b0
created by code.cloudfoundry.org/guardian/metrics.PeriodicMetronNotifier.Start
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/metrics/periodic_metron_notifier.go:82 +0x277

goroutine 39 [select]:
github.com/cloudfoundry/dropsonde/metricbatcher.New.func1(0xc420201000)
	/var/vcap/packages/guardian/src/github.com/cloudfoundry/dropsonde/metricbatcher/metricbatcher.go:34 +0x13e
created by github.com/cloudfoundry/dropsonde/metricbatcher.New
	/var/vcap/packages/guardian/src/github.com/cloudfoundry/dropsonde/metricbatcher/metricbatcher.go:42 +0x155

goroutine 40 [select]:
github.com/cloudfoundry/dropsonde/runtime_stats.(*RuntimeStats).Run(0xc4202b7ca0, 0x0)
	/var/vcap/packages/guardian/src/github.com/cloudfoundry/dropsonde/runtime_stats/runtime_stats.go:33 +0x1bd
created by github.com/cloudfoundry/dropsonde.initialize
	/var/vcap/packages/guardian/src/github.com/cloudfoundry/dropsonde/dropsonde.go:100 +0x255

goroutine 43 [select]:
code.cloudfoundry.org/garden/server/bomberman.(*Bomberman).manageBombs(0xc4201eed80)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/bomberman/bomberman.go:68 +0x6bc
created by code.cloudfoundry.org/garden/server/bomberman.New
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/bomberman/bomberman.go:43 +0x182

goroutine 1838799 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423ba4008)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838717 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4240de000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 45 [chan receive, 942 minutes]:
github.com/tedsuo/ifrit.(*process).Wait.func1(0xc4201eeb80, 0xc4203de420)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:83 +0x44
created by github.com/tedsuo/ifrit.(*process).Wait
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:85 +0x67

goroutine 1838720 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423ba4010)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838810 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d2090)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838797 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0ce30)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838759 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc422e6a000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838795 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d3eb0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838815 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423252f70)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838806 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0c000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838812 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0db58)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838822 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0c030)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838794 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d3ea8)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838719 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0c050)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838796 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4240de030)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838850 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d2010)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838819 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0c010)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838712 [sleep, 1 minutes]:
time.Sleep(0xdf8475800)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/runtime/time.go:59 +0xe1
code.cloudfoundry.org/garden/server/streamer.(*Streamer).Stop.func1(0xc4202b9e60, 0xc42071efd0, 0x3)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/streamer/streamer.go:103 +0x33
created by code.cloudfoundry.org/garden/server/streamer.(*Streamer).Stop
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/streamer/streamer.go:108 +0x8b

goroutine 1838813 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0db60)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838798 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423ba4000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838818 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0d9b8)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838801 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc424109bd0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838811 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423252000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838718 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4240de010)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838817 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc424106000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838721 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc423c0c020)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838800 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc424108720)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838814 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4241092c0)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838816 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d2000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838579 [runnable]:
syscall.readlen(0x8, 0xc420e0ac48, 0x8, 0x3, 0xc4218041c0, 0xe)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/syscall/zsyscall_linux_amd64.go:1084
syscall.forkExec(0xc423c0a560, 0xf, 0xc422b0b700, 0x2, 0x2, 0xc420e0ade0, 0xa65c08, 0xc41fea7a41, 0xc422ca8d00)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/syscall/exec_unix.go:202 +0x33e
syscall.StartProcess(0xc423c0a560, 0xf, 0xc422b0b700, 0x2, 0x2, 0xc420e0ade0, 0x2, 0x4, 0x455d50, 0xc423bee580)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/syscall/exec_unix.go:240 +0x64
os.startProcess(0xc423c0a560, 0xf, 0xc422b0b700, 0x2, 0x2, 0xc420e0af88, 0xc4213de5b0, 0xd, 0xd)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/exec_posix.go:45 +0x1a3
os.StartProcess(0xc423c0a560, 0xf, 0xc422b0b700, 0x2, 0x2, 0xc420e0af88, 0x0, 0x0, 0x0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/doc.go:28 +0x64
os/exec.(*Cmd).Start(0xc420db8b00, 0xc422b0b700, 0xc423c0a540)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/exec/exec.go:358 +0x3c9
os/exec.(*Cmd).Run(0xc420db8b00, 0xa, 0xc420e0b060)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/os/exec/exec.go:276 +0x2b
code.cloudfoundry.org/garden-shed/docker_drivers/aufs.(*Loop).Unmount.func1(0xc423c0a430, 0xc420e0b0d8)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/docker_drivers/aufs/loop.go:36 +0x16c
github.com/eapache/go-resiliency/retrier.(*Retrier).Run(0xc4202006c0, 0xc422b0b440, 0x7, 0xc4203fecc0)
	/var/vcap/packages/guardian/src/github.com/eapache/go-resiliency/retrier/retrier.go:42 +0x32
code.cloudfoundry.org/garden-shed/docker_drivers/aufs.(*Loop).Unmount(0xc4201ff160, 0xc42128fd50, 0x66, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/docker_drivers/aufs/loop.go:43 +0x25d
code.cloudfoundry.org/garden-shed/docker_drivers/aufs.(*QuotaedDriver).Put(0xc420264230, 0xc422b4c580, 0x40, 0x5e3a31, 0xc420c106e0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/docker_drivers/aufs/aufs.go:91 +0x19e
code.cloudfoundry.org/garden-shed/layercake.(*Docker).Remove(0xc4201ff2a0, 0xec52c0, 0xc422e6a230, 0x5e3ed1, 0xc420c106e0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/layercake/docker.go:53 +0x60
code.cloudfoundry.org/garden-shed/layercake.(*AufsCake).Remove(0xc420288cc0, 0xec52c0, 0xc422e6a230, 0xc4204ff180, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/layercake/aufs.go:130 +0x62
code.cloudfoundry.org/garden-shed/layercake/cleaner.(*OvenCleaner).removeRecursively(0xc4201ff360, 0xecee00, 0xc42040c840, 0xecf5a0, 0xc420288cc0, 0xec52c0, 0xc422e6a230, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/layercake/cleaner/cleaner.go:83 +0x5aa
code.cloudfoundry.org/garden-shed/layercake/cleaner.(*OvenCleaner).GC(0xc4201ff360, 0xecee00, 0xc4237332c0, 0xecf5a0, 0xc420288cc0, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/layercake/cleaner/cleaner.go:53 +0x240
code.cloudfoundry.org/garden-shed/rootfs_provider.(*CakeOrdinator).GC(0xc4202642a0, 0xecee00, 0xc423733200, 0x0, 0x0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden-shed/rootfs_provider/cakeordinator.go:92 +0xa6
code.cloudfoundry.org/guardian/gardener.(*Gardener).Create(0xc42026ba40, 0xc4245d4980, 0x39, 0x45d964b800, 0xc422cb3560, 0x24, 0x0, 0x0, 0x0, 0x0, ...)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/guardian/gardener/gardener.go:214 +0x378
code.cloudfoundry.org/garden/server.(*GardenServer).handleCreate(0xc4202a60b0, 0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/request_handling.go:85 +0x3a6
code.cloudfoundry.org/garden/server.(*GardenServer).(code.cloudfoundry.org/garden/server.handleCreate)-fm(0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/server.go:75 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202afd80, 0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/net/http/server.go:1726 +0x44
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc4201fca40, 0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/packages/guardian/src/github.com/bmizerany/pat/mux.go:109 +0x5de
code.cloudfoundry.org/garden/server.New.func1(0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/packages/guardian/src/code.cloudfoundry.org/garden/server/server.go:112 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc4202b7b40, 0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420260700, 0xecb800, 0xc421f7cea0, 0xc4212705a0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4213c0e80, 0xecc500, 0xc4245d47c0)
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/var/vcap/data/packages/golang_1.7.1/13854b532e3b7411e6abeb2e683c530b8114723b/src/net/http/server.go:2293 +0x44d

goroutine 1838834 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc424108000)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

goroutine 1838836 [select]:
github.com/tedsuo/ifrit.(*process).Signal.func1(0xc420200040, 0xeca0c0, 0xc4236d2250)
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:92 +0x112
created by github.com/tedsuo/ifrit.(*process).Signal
	/var/vcap/packages/guardian/src/github.com/tedsuo/ifrit/process.go:96 +0x53

rax    0xca
rbx    0xee4730
rcx    0x460253
rdx    0x0
rdi    0xee5490
rsi    0x0
rbp    0x7ffcab765668
rsp    0x7ffcab765620
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xd3
r14    0xa65c0b
r15    0x3
rip    0x460251
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by scottschulthess** [comment]
[garden.stderr.log.zip](https://github.com/cloudfoundry/guardian/files/1082595/garden.stderr.log.zip)

**Comment by scottschulthess** [comment]
[garden.stdout.log.zip](https://github.com/cloudfoundry/guardian/files/1082596/garden.stdout.log.zip)

**Comment by scottschulthess** [comment]
To clarify this is intermittent and a retry is the solution, but with large deploys this is a problem.   Im deploying using these BOSH settings

```update:
  canaries: 1
  canary_watch_time: 1000-600000
  max_in_flight: 1
  serial: false
  update_watch_time: 1000-600000
```

**Comment by scottschulthess** [comment]
update on this, theory from julz on slack is that it might just be timing out during evac.   i will monitor diego to see if this is the case
